/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SubscriptionTermsRouteImport } from './routes/subscription-terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionTermsRoute = SubscriptionTermsRouteImport.update({
  id: '/subscription-terms',
  path: '/subscription-terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabinet': typeof CabinetRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabinet': typeof CabinetRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabinet': typeof CabinetRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cabinet'
    | '/consent'
    | '/login'
    | '/offer'
    | '/privacy'
    | '/subscription-terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cabinet'
    | '/consent'
    | '/login'
    | '/offer'
    | '/privacy'
    | '/subscription-terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cabinet'
    | '/consent'
    | '/login'
    | '/offer'
    | '/privacy'
    | '/subscription-terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CabinetRoute: typeof CabinetRoute
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  OfferRoute: typeof OfferRoute
  PrivacyRoute: typeof PrivacyRoute
  SubscriptionTermsRoute: typeof SubscriptionTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-terms': {
      id: '/subscription-terms'
      path: '/subscription-terms'
      fullPath: '/subscription-terms'
      preLoaderRoute: typeof SubscriptionTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CabinetRoute: CabinetRoute,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  OfferRoute: OfferRoute,
  PrivacyRoute: PrivacyRoute,
  SubscriptionTermsRoute: SubscriptionTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
