/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DizaynChelovekaRouteImport } from './routes/dizayn-cheloveka'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatricaSudbyRouteImport } from './routes/matrica-sudby'
import { Route as NatalnayaKartaRouteImport } from './routes/natalnaya-karta'
import { Route as NumerologiyaRouteImport } from './routes/numerologiya'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SovmestimostRouteImport } from './routes/sovmestimost'
import { Route as SubscriptionTermsRouteImport } from './routes/subscription-terms'
import { Route as TaroRouteImport } from './routes/taro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DizaynChelovekaRoute = DizaynChelovekaRouteImport.update({
  id: '/dizayn-cheloveka',
  path: '/dizayn-cheloveka',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatricaSudbyRoute = MatricaSudbyRouteImport.update({
  id: '/matrica-sudby',
  path: '/matrica-sudby',
  getParentRoute: () => rootRouteImport,
} as any)
const NatalnayaKartaRoute = NatalnayaKartaRouteImport.update({
  id: '/natalnaya-karta',
  path: '/natalnaya-karta',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerologiyaRoute = NumerologiyaRouteImport.update({
  id: '/numerologiya',
  path: '/numerologiya',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SovmestimostRoute = SovmestimostRouteImport.update({
  id: '/sovmestimost',
  path: '/sovmestimost',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionTermsRoute = SubscriptionTermsRouteImport.update({
  id: '/subscription-terms',
  path: '/subscription-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TaroRoute = TaroRouteImport.update({
  id: '/taro',
  path: '/taro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabinet': typeof CabinetRoute
  '/consent': typeof ConsentRoute
  '/dizayn-cheloveka': typeof DizaynChelovekaRoute
  '/login': typeof LoginRoute
  '/matrica-sudby': typeof MatricaSudbyRoute
  '/natalnaya-karta': typeof NatalnayaKartaRoute
  '/numerologiya': typeof NumerologiyaRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sovmestimost': typeof SovmestimostRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/taro': typeof TaroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabinet': typeof CabinetRoute
  '/consent': typeof ConsentRoute
  '/dizayn-cheloveka': typeof DizaynChelovekaRoute
  '/login': typeof LoginRoute
  '/matrica-sudby': typeof MatricaSudbyRoute
  '/natalnaya-karta': typeof NatalnayaKartaRoute
  '/numerologiya': typeof NumerologiyaRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sovmestimost': typeof SovmestimostRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/taro': typeof TaroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabinet': typeof CabinetRoute
  '/consent': typeof ConsentRoute
  '/dizayn-cheloveka': typeof DizaynChelovekaRoute
  '/login': typeof LoginRoute
  '/matrica-sudby': typeof MatricaSudbyRoute
  '/natalnaya-karta': typeof NatalnayaKartaRoute
  '/numerologiya': typeof NumerologiyaRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sovmestimost': typeof SovmestimostRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/taro': typeof TaroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cabinet'
    | '/consent'
    | '/dizayn-cheloveka'
    | '/login'
    | '/matrica-sudby'
    | '/natalnaya-karta'
    | '/numerologiya'
    | '/offer'
    | '/privacy'
    | '/register'
    | '/sovmestimost'
    | '/subscription-terms'
    | '/taro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cabinet'
    | '/consent'
    | '/dizayn-cheloveka'
    | '/login'
    | '/matrica-sudby'
    | '/natalnaya-karta'
    | '/numerologiya'
    | '/offer'
    | '/privacy'
    | '/register'
    | '/sovmestimost'
    | '/subscription-terms'
    | '/taro'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cabinet'
    | '/consent'
    | '/dizayn-cheloveka'
    | '/login'
    | '/matrica-sudby'
    | '/natalnaya-karta'
    | '/numerologiya'
    | '/offer'
    | '/privacy'
    | '/register'
    | '/sovmestimost'
    | '/subscription-terms'
    | '/taro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CabinetRoute: typeof CabinetRoute
  ConsentRoute: typeof ConsentRoute
  DizaynChelovekaRoute: typeof DizaynChelovekaRoute
  LoginRoute: typeof LoginRoute
  MatricaSudbyRoute: typeof MatricaSudbyRoute
  NatalnayaKartaRoute: typeof NatalnayaKartaRoute
  NumerologiyaRoute: typeof NumerologiyaRoute
  OfferRoute: typeof OfferRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SovmestimostRoute: typeof SovmestimostRoute
  SubscriptionTermsRoute: typeof SubscriptionTermsRoute
  TaroRoute: typeof TaroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dizayn-cheloveka': {
      id: '/dizayn-cheloveka'
      path: '/dizayn-cheloveka'
      fullPath: '/dizayn-cheloveka'
      preLoaderRoute: typeof DizaynChelovekaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrica-sudby': {
      id: '/matrica-sudby'
      path: '/matrica-sudby'
      fullPath: '/matrica-sudby'
      preLoaderRoute: typeof MatricaSudbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natalnaya-karta': {
      id: '/natalnaya-karta'
      path: '/natalnaya-karta'
      fullPath: '/natalnaya-karta'
      preLoaderRoute: typeof NatalnayaKartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerologiya': {
      id: '/numerologiya'
      path: '/numerologiya'
      fullPath: '/numerologiya'
      preLoaderRoute: typeof NumerologiyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sovmestimost': {
      id: '/sovmestimost'
      path: '/sovmestimost'
      fullPath: '/sovmestimost'
      preLoaderRoute: typeof SovmestimostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-terms': {
      id: '/subscription-terms'
      path: '/subscription-terms'
      fullPath: '/subscription-terms'
      preLoaderRoute: typeof SubscriptionTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taro': {
      id: '/taro'
      path: '/taro'
      fullPath: '/taro'
      preLoaderRoute: typeof TaroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CabinetRoute: CabinetRoute,
  ConsentRoute: ConsentRoute,
  DizaynChelovekaRoute: DizaynChelovekaRoute,
  LoginRoute: LoginRoute,
  MatricaSudbyRoute: MatricaSudbyRoute,
  NatalnayaKartaRoute: NatalnayaKartaRoute,
  NumerologiyaRoute: NumerologiyaRoute,
  OfferRoute: OfferRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SovmestimostRoute: SovmestimostRoute,
  SubscriptionTermsRoute: SubscriptionTermsRoute,
  TaroRoute: TaroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
